---
- name: print "Hello, World" on localhost
  hosts: webserver
  gather_facts: false

  tasks:
    - name: Print message
      debug:
        msg: "Hello, AWS"
    
    - name: Display index.html from httpd
      ansible.builtin.shell: cat /var/www/html/index.html
      register: index

    - debug: var=index    
