---
- name: Execute shell command on managed nodes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run shell command
      ansible.builtin.shell: ls -al
      register: shell_output
    - name: Display shell command output
      debug:
        var: shell_output.stdout





