---
- name: Install Jenkins on Instance
  hosts: Jenkins
  gather_facts: false
  tasks:
    - name: Ping 
      ping:
    
    - name: Download Jenkins repository key and store
      ansible.builtin.shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      
    - name: Update APT with Jenkins
      ansible.builtin.shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update APT package
      ansible.builtin.shell: sudo apt-get update
    
    - name: Install Java Openjdk package
      apt:
        name: openjdk-11-jre
        state: present
    
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service: 
        name: jenkins
        state: started
...
